name: Weekly FBX SDK Update

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download SDKs
      run: |
        wget --user-agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" -O fbx202021_fbxsdk_vs2019_win.exe "https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_win.exe"
        wget --user-agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" -O fbx202021_fbxsdk_clang_mac.pkg.tgz "https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_clang_mac.pkg.tgz"
        wget --user-agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" -O fbx202021_fbxsdk_linux.tar.gz "https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_linux.tar.gz"

    - name: Upload SDK for Windows
      uses: actions/upload-artifact@v4
      with:
        name: Windows-SDK
        path: fbx202021_fbxsdk_vs2019_win.exe

    - name: Upload SDK for macOS
      uses: actions/upload-artifact@v4
      with:
        name: macOS-SDK
        path: fbx202021_fbxsdk_clang_mac.pkg.tgz

    - name: Upload SDK for Linux
      uses: actions/upload-artifact@v4
      with:
        name: Linux-SDK
        path: fbx202021_fbxsdk_linux.tar.gz